import Head from "next/head";
import React, {  useState } from "react";
import { Button, Layout, Menu, message, Popover } from "antd";
import "antd/dist/antd.css";
import type { MenuProps } from "antd";
import Link from "next/link";
import Image from "next/image";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  DashboardOutlined,
  SolutionOutlined,
  TeamOutlined,
  DeploymentUnitOutlined,
  ReadOutlined,
  ProjectOutlined,
  FileAddOutlined,
  EditOutlined,
  MessageOutlined,
} from "@ant-design/icons";
import logo from "../public/logo.png";
import styled from "styled-components";
import axios, { AxiosResponse } from "axios";
import { useRouter } from "next/router";
import { BaseURL } from "../service/api";

const { Header, Sider, Content } = Layout;

const ImageContainer = styled.div`
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 10;
  position: sticky;
  top: 0;
`;
const StyledHeader = styled(Header)`
  padding: 0 50px;
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 9;
`;
const LogoutButton = styled(Popover)`
  display: flex;
  align-items: center;
  justify-content: center;
`;
const StyledContent = styled(Content)`
  margin: 24px 16px;
  padding: 24;
  min-height: calc(100vh - 128px);
  background-color: white;
`;

type MenuItem = Required<MenuProps>["items"][number];

export default function MainLayout({ children }: React.PropsWithChildren<{}>) {
  const getItem = (
    label: React.ReactNode,
    key: React.Key,
    icon?: React.ReactNode,
    children?: MenuItem[],
    type?: "group"
  ): MenuItem =>
    ({
      key,
      icon,
      children,
      label,
      type,
    } as MenuItem);

  // menu items
  const items = [
    getItem(
      <Link href="/dashboard/manager">Overview</Link>,
      "manager",
      <DashboardOutlined />
    ),
    getItem("Student", "sub1", <SolutionOutlined />, [
      getItem(
        <Link href="/dashboard/manager/students">Student List</Link>,
        "students",
        <TeamOutlined />
      ),
    ]),
    getItem("Teacher", "sub2", <DeploymentUnitOutlined />, [
      getItem(
        <Link href="/dashboard/manager/teachers">Teacher List</Link>,
        "teachers",
        <TeamOutlined />
      ),
    ]),
    getItem("Course", "sub3", <ReadOutlined />, [
      getItem(
        <Link href="/dashboard/manager/courses">All Course</Link>,
        "courses",
        <ProjectOutlined />
      ),
      getItem(
        <Link href="/dashboard/manager/courses/add-course">Add Course</Link>,
        "add-course",
        <FileAddOutlined />
      ),
      getItem(
        <Link href="/dashboard/manager/courses/edit-course">Edit Course</Link>,
        "edit-course",
        <EditOutlined />
      ),
    ]),
    getItem(
      <Link href="/dashboard/manager/message">Message</Link>,
      "message",
      <MessageOutlined />
    ),
  ];

  const router = useRouter();
  const [collapsed, setCollapsed] = useState(false);
  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };

  // to get current selected keys of menu & subMenu
  const currentPath = router.pathname.split("/");
  const currentMenuKey = currentPath.pop() as string;

  const [path, setPath] = useState([""]);
  // console.log("path:", path);
  // console.log("items:", items);


  const logout = async () => {
    const token = JSON.parse(localStorage.getItem("cms-user") as string).token;
    try {
      const res: AxiosResponse = await axios.post(
        `${BaseURL}/logout`,
        {},
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );
      if (res) {
        localStorage.removeItem("cms-user");
        router.push("/");
      }
    } catch (err: any) {
      message.error(err.response.data.msg);
    }
  };

  return (
    <>
      <Head>
        <title>Course Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout style={{height: '100%'}}>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapsed}
          width={222}
          defaultCollapsed={true}
          collapsedWidth={100}
        >
          <ImageContainer>
            <Link href="/" passHref>
              <span style={{ cursor: "pointer" }}>
                <Image src={logo} alt="logo" width="70" height="70" />
              </span>
            </Link>
          </ImageContainer>

          <Menu
            theme="dark"
            mode="inline"
            inlineCollapsed={collapsed}
            style={{ position: "sticky", top: "80px", fontSize: "16px" }}
            items={items}
            selectedKeys={[currentMenuKey]}
            // openKeys={[]}
          >
            
          </Menu>
        </Sider>

        <Layout className="site-layout">
          <StyledHeader className="site-layout-background">
            {/* collapsedButton */}
            <Button
              icon={collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
              onClick={toggleCollapsed}
              size="large"
              type="text"
              style={{
                color: "white",
                border: "none",
                backgroundColor: "transparent",
              }}
            />

            <LogoutButton
              content={
                <Button type="link" onClick={logout}>
                  Logout
                </Button>
              }
              trigger="hover"
            >
              <Button icon={<UserOutlined />} shape="circle" />
            </LogoutButton>
          </StyledHeader>

          <StyledContent className="site-layout-background ">
            {children}
          </StyledContent>
        </Layout>
      </Layout>
    </>
  );
}
