import Head from "next/head";
import React, { ReactNode, useState } from "react";
import { Button, Layout, Menu, Tabs } from "antd";
import "antd/dist/antd.css";
import type { MenuProps } from "antd";
import Link from "next/link";
import Image from "next/image";
import {
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  UserOutlined,
  AppstoreOutlined,
} from "@ant-design/icons";
import logo from "../public/logo.png";
import styled from "styled-components";

const { Header, Sider, Content } = Layout;

const ImageContainer = styled.div`
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index:10;
`;
const StyledHeader = styled(Header)`
  padding: 0 50px;
  height: 80px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 9;
`;
const ButtonContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
`;
const StyledContent = styled(Content)`
  margin: 24px 16px;
  padding: 24;
  min-height: calc(100vh - 128px);
  background-color: white;
`;

type MenuItem = Required<MenuProps>["items"][number];

export default function MainLayout({ children }: React.PropsWithChildren<{}>) {
  const [collapse, setCollapse] = useState(false);
  const toggle = () => {
    setCollapse(!collapse);
  };

  const getItem = (
    label: string,
    key: string,
    icon?: React.ReactNode,
    children?: MenuItem[],
    type?: "group"
  ) => {
    return {
      key,
      icon,
      children,
      label,
      type,
    };
  };

  const items = [
    getItem("overview", "1", <AppstoreOutlined />),
    getItem("student", "sub1", <AppstoreOutlined />, [
      getItem("student list", "2"),
    ]),
    getItem("teacher", "sub2", <AppstoreOutlined />, [
      getItem("teacher list", "3"),
    ]),
    getItem("course", "sub3", <AppstoreOutlined />, [
      getItem("all course", "4"),
      getItem("add course", "5"),
      getItem("edit course", "6"),
    ]),
    getItem("message", "7", <AppstoreOutlined />),
  ];

  return (
    <>
      <Head>
        <title>Course Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider
          trigger={null}
          collapsible
          collapsed={collapse}
          width={222}
          defaultCollapsed={true}
          collapsedWidth={100}
        >
            <ImageContainer>
              <Link href="/" passHref>
                <span style={{ cursor: "pointer" }}>
                  <Image src={logo} alt="logo" width="70" height="70" />
                </span>
              </Link>
            </ImageContainer>
          <Menu
            theme="dark"
            mode="inline"
            inlineCollapsed={collapse}
            style={{ position: "sticky", top: "80px" }}
            items={items}
          >
            
          </Menu>
        </Sider>

        <Layout className="site-layout">
          <StyledHeader className="site-layout-background">
            {React.createElement(
              collapse ? MenuUnfoldOutlined : MenuFoldOutlined,
              {
                className: "trigger",
                style: { fontSize: "30px", color: "white" },
                onClick: toggle,
              }
            )}
            <ButtonContainer>
              <Button icon={<UserOutlined />} shape="circle" />
            </ButtonContainer>
          </StyledHeader>

          <StyledContent className="site-layout-background ">
            {children}
          </StyledContent>
        </Layout>
      </Layout>
    </>
  );
}
