import type { NextPage } from "next";
import Head from "next/head";
import "antd/dist/antd.css";
import styled from "styled-components";
import {
  Button,
  Checkbox,
  Col,
  Form,
  Input,
  Radio,
  Row,
  Typography,
} from "antd";
import { UserOutlined, LockOutlined } from "@ant-design/icons";

const { Title } = Typography;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  height: 100vh;
  place-content: center;
`;

const Home: NextPage = () => {
  const onFinish = (e) => {
    console.log(e)
  }


  return (
    <div>
      <Head>
        <title>Course Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row align="middle" justify="center">
        <Col span={12}>
          <Container>
            <Title level={1} style={{placeSelf:"center", marginBottom:"50px"}}>Course Management Assistant</Title>
            <Form
              name="normal_login"
              className="login-form"
              size="large"
              initialValues={{ remember: true, role: "student" }}
              onFinish={onFinish}
            >
              <Form.Item rules={[{ required: true }]} name="role">
                <Radio.Group>
                  <Radio.Button value="student">Student</Radio.Button>
                  <Radio.Button value="teacher">Teacher</Radio.Button>
                  <Radio.Button value="manager">Manager</Radio.Button>
                </Radio.Group>
              </Form.Item>

              <Form.Item
                name="email"
                rules={[
                  { required: true, message: '"email" is required' },
                  { type: "email" },
                ]}
              >
                <Input
                  prefix={<UserOutlined className="site-form-item-icon" />}
                  placeholder="Please input email"
                />
              </Form.Item>

              <Form.Item
                name="password"
                rules={[
                  { required: true, message: '"password" is required' },
                  { min: 4, max: 16 },
                ]}
              >
                <Input
                  prefix={<LockOutlined className="site-form-item-icon" />}
                  type="password"
                  placeholder="Please input password"
                />
              </Form.Item>
              <Form.Item>
                <Form.Item name="remember" valuePropName="checked" noStyle>
                  <Checkbox>Remember me</Checkbox>
                </Form.Item>
              </Form.Item>

              <Form.Item>
                <Button
                  type="primary"
                  htmlType="submit"
                  className="login-form-button"
                  style={{
                    display: "block",
                    width: "100%",
                    padding: "4px 15px",
                  }}
                >
                  LogIn
                </Button>
              </Form.Item>
            </Form>
          </Container>
        </Col>
      </Row>
    </div>
  );
};

export default Home;
